const profileActionType={
    PROFILE_START:'PROFILE_START',
    PROFILE_SUCCESS:'PROFILE_SUCCESS',
    PROFILE_ERROR:'PROFILE_ERROR',
    PROFILE_UPDATE:'PROFILE_UPDATE',
    PROFILE_UPDATE_DONE:'PROFILE_UPDATE_DONE'

}

export default profileActionType