const profileActionType={
    PROFILE_START:'PROFILE_START',
    PROFILE_SUCCESS:'PROFILE_SUCCESS',
    PROFILE_ERROR:'PROFILE_ERROR',
    PROFILE_JOB:'PROFILE_UPDATE'

}

export default profileActionType